apiVersion: v1
kind: Service
metadata:
  name: signer-service
spec:
  selector:
    app: signer-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
   -  protocol: TCP
      port: 8082
      targetPort: 8082